# Generated by Django 3.0.6 on 2020-06-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContributedOrganization',
            new_name='Contribute',
        ),
        migrations.RenameModel(
            old_name='MatchingOrganization',
            new_name='Match',
        ),
        migrations.AlterModelOptions(
            name='contribute',
            options={'ordering': ['created'], 'verbose_name': 'Contributing Organization'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['created'], 'verbose_name': 'Matching Organization'},
        ),
    ]
