# Generated by Django 3.0.6 on 2020-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200602_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
