# Generated by Django 3.0.6 on 2020-06-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200603_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
